# Set theme
remote_theme: daviddarnes/alembic

# File excludes
exclude:
- README.md
- Gemfile
- Gemfile.lock

# Set plugins
plugins:
- jekyll-sitemap
- jekyll-mentions
- jekyll-paginate
- jekyll-seo-tag
- jekyll-redirect-from
- jekyll-default-layout
- jekyll-feed
- jemoji
- jekyll-remote-theme

# 3. Gem settings
paginate: 2 # jekyll-paginate > items per page
paginate_path: blog/page:num # jekyll-paginate > blog page
jekyll-mentions: https://twitter.com # jekyll-mentions > service used when @replying
twitter: 
  username: landongetz # jekyll-seo-tag > Owners twitter username
author: LandonGetz # jekyll-seo-tag > default author
social: # jekyll-seo-tag > social overrides
  name: Landon Getz # jekyll-seo-tag > real name
  links:  # jekyll-seo-tag > social aliases (sameAs)
    - https://twitter.com/landongetz
    - https://www.facebook.com/landon.getz
    - https://www.linkedin.com/in/landon-getz-19a473111
    - https://github.com/landongetz
    
# Site settings
title: 'Landon Getz - Blog'
permalink: pretty
logo: "/assets/logo.svg"
encoding: utf-8 # Make sure the encoding is right
lang: en-GB # Set the site language
title: "Landon Getz" # Site name or title, also used in jekyll-seo-tag
logo: "/assets/logo.svg" # Site logo, also used in jekyll-seo-tag
description: "Welcome to the rantings of a queer scientist, advocate, baker, and teacher." # Site description and default description, also used in jekyll-seo-tag
url: "" # Site url, also used in jekyll-seo-tag
baseurl: "/blog"
repo: "https://github.com/landongetz/blog"
email: "landon.getz@dal.ca"
# disqus: "alembic-1" # Blog post comments, uncomment the option and set the site ID from your Disqus account
avatarurl: "https://s.gravatar.com/avatar/00973bfb820b39a6c8ca08f65ac3d811?s=80" # Uses avatars for favicons to get multple sites, eg Gravatar, Twitter, GitHub
# google_analytics: ''
# service_worker: false # Will turn off the service worker if set to false
css_inline: true # Will insert all styles into a single <style> block in the <head> element and remove the style <link> reference

# 6. Jekyll collections settings
defaults:
  -
    scope:
        path: ""
    values:
        image: "/blog/assets/default-social-image.jpg" # Default image for sharing

# Pagination
paginate: 5
paginate_path: blog/page:num

navigation_header:
  Home: /
  Blog: /blog/
  Categories: /categories/
  Search: /search/
  CV: http://www.landongetz.com


navigation_footer:
  Created by David Darnes: https://darn.es/

social_links: # Appears in sidebar. Set the urls then uncomment and comment out as desired
  Twitter: https://twitter.com/landongetz
  LinkedIn: https://www.linkedin.com/in/landon-getz-19a473111
  GitHub: https://github.com/landongetz
  link: http://landongetz.com

sharing_links: # Appear at the bottom of single blog posts, uncomment and comment out as desired. Colours set the button colour
  Twitter: "#0d94e7"
  facebook: "#3B5998"
  # Google+: "#DC4E41"
  # Pinterest: "#BD081C"
  LinkedIn: "#0077B5"
  # tumblr: "#36465D"
  # Reddit: "#FF4500"
  # Hacker News: "#ff6600"
  # Designer News: "#2D72D9"
  Email: ""
  
# Footer nav
navigation_footer:
  Back to top: "#top"

# Collections
collections:
  posts:
    title:
    output: true
    description: ""
    feature_text: |
        
    feature_image: "/blog/images/IMG_0201.jpg"
